# This workflow is used to automatically update the `cargo-generate` branch. If you copied the
# template, you can safely delete this. :)
#
# BE VERY CAREFUL about what this workflow runs, since IT HAS THE ABILITY TO DELETE THE ENTIRE
# REPOSITORY'S CONTENTS. For reason, stick to pre-installed tools and trusted actions (such as
# those hosted from the `actions` organization.)

name: Update `cargo-generate` branch

on:
  # Update `cargo-generate` from `main` every time `main` is updated.
  push:
    branches: main
  # Allow this workflow to be manually triggered.
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    # TODO: Change this to `TheBevyFlock`.
    if: ${{ github.repository == 'BD103/bevy_quickstart' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # Fetch entire history, since we need it all to successfully merge.
          fetch-depth: 0
          # Specify a personal access token, since the default one does not let workflows modify
          # the `.github/workflows` folder. This PAT needs write permissions for Contents and
          # Workflows. I recommend creating a scoped token that only has access to this repository.
          token: ${{ secrets.CARGO_GENERATE_PAT }}

      - name: Configure Git user
        env:
          # From https://github.com/actions/checkout/pull/1707.
          NAME: github-actions[bot]
          EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
        run: |
          git config user.name $NAME
          git config user.email $EMAIL

      - name: Switch to `cargo-generate` branch
        run: git checkout cargo-generate

      - name: Merge `main` branch into `cargo-generate`
        id: merge
        # We use `--no-edit` to prevent any editor from being opened, since we can't close it.
        run: git merge main --no-edit --verbose

      - name: Handle merge conflict
        # Only run this if merging failed.
        if: ${{ failure() && steps.merge.outcome == 'failure' }}
        env:
          TITLE: Failed to auto-update `cargo-generate`
          BODY: |
            There were merge conflicts while trying to update `cargo-generate` from `main`. You can
            do it manually by running:

            ```bash
            # Update your local copy of the `main` branch.
            git switch main
            git pull
            # Checkout the `cargo-generate` branch.
            git checkout cargo-generate
            # Merge changes from `main` to `cargo-generate`. You will have to fix merge conflicts.
            git merge main
            ```

            _This is an automated message created using `cargo-generate.yaml`._
        # The messages must be in quotes, since they contain spaces.
        run: gh issue create --title "$TITLE" --body "$BODY"

      - name: Push changes
        # Only run if merging succeeded.
        if: ${{ success() && steps.merge.outcome == 'success' }}
        run: git push
